(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,602,103,164],[105,602,50,132],[157,602,30,64],[89,768,93,117],[0,0,160,600],[0,768,87,145]]}
];


// symbols:



(lib.nineteenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.nineteencheese = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.nineteencrackers = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.nineteenshrimp = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nineteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.nineteentopright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgQFAy9MAAAhl5MAgLAAAMAAABl5g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-103,-326,206.1,652.2), null);


(lib.smallbitesplatters = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape.setTransform(37.8,48.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgmA/QgGgCAAgGQAAgEAGgCIADgCQAEgCABgDIABgPIAAgIIAAgKIAAgIQAAgXgBgGQgBgIgDgBIgFgCQgIgCAAgFQAAgDACgCQADgDAFgBIARgGIAMgCQAGAAACARIAAACIAAABQAHgKAHgGQAHgFAHAAQAJAAAFAFQAGAGAAAJQAAAJgEAEQgEAGgIAAIgGgBIgFgFIgDgEQgBgBAAgBQAAgBgBAAQAAgBAAAAQAAAAgBAAQgJAAgDANQgDAMAAAlQAAALABAGQABAFAEACIAFABQAHADAAAFQAAAFgHACQgHACgQAAQgUAAgGgCg");
	this.shape_1.setTransform(26.5,48.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgtAwQgTgTABgdQgBgbAUgTQASgTAcAAQAbAAASASQARARAAAcQAAAdgSAUQgTATgbAAQgcAAgRgSgAgYglQgHAKAAARQAAAZAKARQALAQAOAAQANAAAIgKQAIgLgBgRQABgYgLgQQgLgRgOAAQgNAAgIAKg");
	this.shape_2.setTransform(14.3,48.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAwBaQgIgCAAgGQAAgFAIgDIAGgDQACgCABgFQABgGAAgRIAAgHIAAg1IAAggIgRAqQglBhgIAAQgEAAgHgOQgHgNgTgpIgbhAIgBAyIAAAiIABAYQAAAGACABIAGADQAHADABAFQAAAFgHADQgGACgQAAQgOAAgGgCQgHgDABgFQAAgFAGgDQAIgDAAgDQABgGADghQACgfAAgpIAAgEIgBgRQgCgFgDgCIgFgCQgJgDAAgGQAAgFAGgCQAGgCASAAIASABIAGABQACACAJAWIAHASIADAJQAfBMACAAQADAAALgbQAMgbAPgsIADgIQAEgOAFgEQACgDAEgBIASgBQARAAAGACQAFACAAAFQABAGgIACIgEACQgDACgBAFQgCAFAAATIACBIIACAlQABADAGACIACABIAFADQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQgBAGgGACQgIACgUAAQgUAAgGgCg");
	this.shape_3.setTransform(-4.4,45.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhMBNQgYgSAAgeQABgQAHgNQAIgLAQgMIABgBQgGgFgCgHQgDgGgBgHQAAgTAPgNQAPgNAXAAQAPAAALAGQAKAGAAAIQAAADgCACQgDACgEAAIgJgDQgJgEgIAAQgJAAgGAHQgHAHAAALQABAFABADQACAEADADQADADAGADIAHACIADACIABABQgBADgEAFQgFAGgEAAIgFgBIgJgEQgIAHgDAIQgEAJAAALQAAAYAQAQQAQAQAYAAQAVAAAMgLQANgKAAgRQgBgLgFgHQgEgGgJAAQgJAAgFAFQgGAFAAAIIAAADIAAABIgCABIgBAAQgFAAgDgDQgCgEAAgGQAAgTA3gZIADgCQAPgGAIgIQAHgIAAgJQAAgGgDgDQgDgDgHAAIgFABIgFAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgCgCAAgDQAAgGAHgDQAHgEALAAQAOAAAIAHQAHAIAAANQAAAQgNANQgOANgdAKQANAEAFAKQAHAJAAANQgBAKgDAJQgEAJgHAIQgMAMgRAHQgSAGgVAAQgnAAgXgSg");
	this.shape_4.setTransform(-33,45.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgJBCIgNgCIgEACIgEABIgDgBIgCgCQgEgDgEgKQgEgLAAgJQAAgEACgDQADgCADAAQAGAAAGAKIAFAHQADAFAHADQAGADAHAAQAIAAAFgEQAFgEAAgHQAAgLgUgKIgHgEQgUgKgHgHQgHgIAAgMQAAgRALgKQAMgLASAAIAIABIAJABIAGgCIAEgBQAGAAAGAKQAGAKAAALQAAAFgCACQgCADgDAAQgDAAgDgDQgDgCgEgGQgFgIgFgDQgFgDgHAAQgGAAgFAEQgEAEAAAHQAAAGAEAEQAFAFAPAHIABABQAkARAAAUQAAASgOAMQgNAMgVAAg");
	this.shape_5.setTransform(38.4,18);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgmA/QgGgCAAgFQAAgFAGgCIADgBQAEgCABgFIABgOIAAgIIAAgLIAAgGQAAgXgBgIQgBgGgDgCIgFgCQgIgDAAgEQAAgDACgCQADgDAFgCIARgFIAMgDQAGAAACASIAAACIAAABQAHgLAHgEQAHgGAHAAQAJAAAFAGQAGAFAAAIQAAAKgEAFQgEAEgIAAIgGgBIgFgDIgDgGQgBAAAAgBQAAgBgBAAQAAgBAAAAQgBAAAAAAQgJAAgDAMQgDANAAAlQAAAMABAFQABAGAEABIAFACQAHACAAAGQAAAEgHACQgHACgQAAQgUAAgGgCg");
	this.shape_6.setTransform(28.5,17.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAAAQABABAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_7.setTransform(16.6,18);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgGBNQgHgCgEgFQgEgEgCgHQgCgHAAgTIAAhDIgMAAIgDgBIgBgDIAAgEQgBgDANgMIAGgFIAEgEQAOgMAFAAIADACIABADIAAAYIAcAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABIABAEIAAAEIgBAEQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgaAAIgCABIAAADIAAA+QAAAQACAEQAEAEAGAAQAFAAAGgCIAJgCQABABAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAGgLAHQgLAGgNABQgHAAgGgCg");
	this.shape_8.setTransform(5.5,16.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgGBNQgHgCgEgFQgEgEgCgHQgCgHAAgTIAAhDIgMAAIgEgBIAAgDIAAgEQgBgDANgMIAGgFIAEgEQAOgMAFAAIADACIABADIAAAYIAcAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABIABAEIAAAEIgBAEQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgaAAIgCABIAAADIAAA+QAAAQACAEQAEAEAGAAQAFAAAGgCIAJgCQABABAAAAQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAGgLAHQgLAGgNABQgHAAgGgCg");
	this.shape_9.setTransform(-3.5,16.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAXA8IgHgHIgGADQgPALgPgBQgTAAgMgLQgLgLAAgRQAAgUAPgKQAPgMAaAAQAGAAAEACQADACAAAEQAAAHgJAAQgMAAgIAHQgHAFAAALQAAALAGAFQAGAHAMgBQAMAAAFgFQAFgFAAgOIAAgvQAAgLgFgHQgEgFgJgBQgGABgFADQgGACgEAGIgEADQgHAKgJAAQgFAAgCgDQgEgDAAgGQAAgMAPgIQAPgIAXAAQANAAALADQAKAEAFAHQAEAFABAIQACAHAAATIAAAnIABALQABAEADABIAEABQAIACAAAFQAAAGgJAFQgIAEgMAAQgFAAgGgGg");
	this.shape_10.setTransform(-14.7,18.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_11.setTransform(-25.4,15.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AhBBaQgHgCAAgGQAAgFAIgDIAFgDQADgCABgPIABg2IgBgwQgBgSgCgDQgBgCgHgCQgGgDAAgFQAAgFAEgCQAEgCAHAAIAOAAIAOAAIAagBIATAAQAdAAAOAMQAOAMAAAYQAAAbgRAOQgSANghAAQgMAAAAgIQAAgJAKAAQAQAAAKgIQAKgJAAgSQAAgSgKgIQgLgIgTAAIgOABQgDABgCAEIgBALIAAAbIAAA3IAAAkQABAKACACIAGACQAIADAAAFQAAAGgHACQgHACgUAAQgUAAgHgCg");
	this.shape_12.setTransform(-36,15.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgNAnQgBgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIACgFIACgEIAIgOIACgJIAAgDIgEgCQgHgDgDgEQgDgFAAgHQAAgIAFgFQAFgGAIAAQAIAAAFAIQAGAHAAALQAAAJgEAIQgCAKgJANIgGAKQgDADgCAAQgDAAgDgBg");
	this.shape_13.setTransform(65.7,-5.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgJBCIgNgCIgEACIgEABIgDgBIgCgCQgEgDgEgKQgEgLAAgJQAAgEACgDQADgCADAAQAGAAAGAKIAFAHQADAFAHADQAGADAHAAQAIAAAFgEQAFgEAAgHQAAgLgUgKIgHgEQgUgKgHgHQgHgIAAgMQAAgRALgKQAMgLASAAIAIABIAJABIAGgCIAEgBQAGAAAGAKQAGAKAAALQAAAFgCACQgCADgDAAQgDAAgDgDQgDgCgEgGQgFgIgFgDQgFgDgHAAQgGAAgFAEQgEAEAAAHQAAAGAEAEQAFAFAPAHIABABQAkARAAAUQAAASgOAMQgNAMgVAAg");
	this.shape_14.setTransform(56.3,-12.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_15.setTransform(44.2,-12.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgGBMQgGgCgFgEQgFgEgBgHQgCgHAAgTIAAhDIgMAAIgDgBIgBgEIAAgCQAAgEAMgMIAGgEIAEgFQAOgLAFAAIADAAIACADIAAAYIAcAAQAAAAABABQABAAAAAAQABAAAAAAQABAAAAAAIABAGIAAACIgBAGQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgbAAIgBABIgBADIAAA+QAAAQACAEQAEAFAGAAQAFAAAGgCIAJgDQABAAAAABQABAAAAAAQABAAAAAAQABABABAAQAAAAAAABQABABAAAAQAAABAAAAQAAABAAAAQABAIgLAGQgLAHgOgBQgHAAgGgCg");
	this.shape_16.setTransform(33.1,-13.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgWBbQgGgCAAgGQAAgEAGgCIADgCQAEgCABgEQACgEgBgKIAAgIIAAgLIAAgNIgBgZQAAgGgDgBIgGgCQgIgDAAgEQAAgDACgCQADgDAFgCIATgGIANgCQAEAAABACQACADAAAFIAAAIIgBAGIgBAfIAAABIAAAfIABARQABAFADACIAEACQAHACAAAFQAAAFgGACQgGACgRAAQgSAAgHgCgAgPg/QgFgFAAgGQAAgHAGgGQAGgFAIAAQAHAAAGAFQAGAFAAAHQgBAGgFAFQgGAFgJAAQgHAAgGgEg");
	this.shape_17.setTransform(24.9,-15.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AgIBbIgaAAIgMAAIgOAAQgJAAgEgCQgFgCAAgFQAAgFAHgDQAGgCACgCQACgDAAgTIABgwIgBgwQAAgSgCgDQgCgCgGgCQgHgDAAgFQAAgFAEgCQADgCAJAAIANAAIAPAAIAZgBIATAAQAcgBAPAMQAOAMAAAUQAAASgKALQgLAKgTAEQAZACANAMQAOAMAAAWQAAAXgRAOQgRANgfgBgAgShJQgFABgBACQgCAEgBAMIAAAkIAAA0IAAAZQABAHACAEQABACAHACQAGACAKgBQAVABAKgKQAMgIAAgRQAAgSgNgJQgMgIgXAAQgLAAABgHQgBgJALAAQAQAAALgHQALgIAAgRQAAgQgKgIQgKgIgUAAg");
	this.shape_18.setTransform(12.5,-15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_19.setTransform(-6.9,-15.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_20.setTransform(-14,-15.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AAXA7IgHgGIgFADQgQALgQAAQgSgBgLgKQgMgMAAgRQAAgUAPgLQAPgLAaAAQAGAAAEACQACACAAAFQAAAGgIAAQgMAAgIAGQgHAHgBAKQABAKAGAHQAHAFALABQAMAAAFgGQAFgGAAgNIAAgvQAAgMgFgFQgFgHgIABQgGAAgFACQgFADgFAFIgEAEQgHAKgJAAQgFAAgCgEQgEgDAAgFQAAgMAPgJQAPgIAXAAQANAAAKAFQALADAFAHQAEAFABAHQACAJAAARIAAApIABALQABADADAAIAEACQAIACAAAEQAAAHgJAEQgIAGgMAAQgFAAgGgIg");
	this.shape_21.setTransform(-23.9,-12.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AA5A/QgHgCAAgFQABgFAGgDIAEgBQAEgCABgGIABgVQAAglgFgLQgFgJgOgBQgOAAgHAOQgGAMAAAfIAAAGQAAAOACAEQAAAFAEABIADACQAGACAAAEQABAGgHACQgFACgUAAQgRAAgGgCQgGgCAAgFQAAgEAGgDIAGgCQACgCABgFIABgUQAAgngEgKQgGgLgOAAQgGAAgGAFQgGADgEAHQgCAHgBAKIgCAhQAAAMACAEQABAEACACIAFACQAGADAAAEQAAAFgFADQgHABgRAAQgTAAgHgCQgFgCgBgGQABgEAFgCIAEgCQADgBABgFQACgEAAgJIAAgJIgBgKIAAgIIAAgdQgCgIgCgBIgGgCQgHgDgBgEQABgDACgCIAIgEIASgGIANgDQADAAACACQACACAAAFIAAAGIAAACIABACIAAAAIABAAIAAgBIADgDIABgBQAQgOAQAAQAFAAAGACQAGABAEAEQAEADAFAGIAGAFQABAAAEgDIAFgGQAJgHAGgCQAGgDAHAAQAPAAALAGQALAGAGAKQAFANAAAkIAAAMIAAAHIAAAGQAAAHACAEQAAADAEABIADACQAGACAAAEQABAGgHACQgFACgUAAQgTAAgFgCg");
	this.shape_22.setTransform(-42.6,-12.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AgfBcQgOgEgJgEQgFgEgDgLQgDgLgBgOQAAgFACgEQADgDAEAAQAGAAAGALIAEAGQAHAOAKAGQAJAHANAAQAOAAAJgIQAKgIAAgMQAAgSglgRIgEgBQgfgNgKgLQgKgMAAgRQAAgYARgOQAQgPAbAAIAPABIARAEIAGgDIAEgBQADAAADACQACACACAFQAFAHACAJQADAIAAAGQAAAFgCACQgDACgDAAQgGAAgHgJIgCgCQgHgKgJgEQgIgEgLgBQgNABgIAGQgIAHAAAMQAAAKAGAHQAIAGAaAMIAFACQAXAKAKAIQAHAHAEAIQADAJAAAKQABAagTAOQgSAPggAAQgPAAgOgDg");
	this.shape_23.setTransform(-61.5,-14.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("Ag6BUQgGgFAAgIQAAgHAEgEQAFgFAGAAIAGABIAEADIADAFQADAFADAAQAGAAAHgKQAGgJAAgKQAAgLgIgUIgCgDIgUgsIgMgYQgCgFgHgDIgBAAQgEgCgBgCQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgGAHgCQAGgCATAAQATAAAGACQAGACAAAFIgBAEIgCACIgFACQgFACAAADIADAJIAKAaIAKAXQADAGACAAQABAAADgGIAIgUIAKgZQADgJAAgDQAAgEgHgEQgHgEAAgDQAAgEAFgCQAGgCAPAAQAPAAAFACQAGACAAAFQAAAFgIABIgFACQgHAEgIAWIgEAKIgQAoQgVA0gNAQQgNAQgTAAQgJAAgGgFg");
	this.shape_24.setTransform(38.3,-39.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E46").s().p("AAXA8IgHgHIgGADQgOAKgQAAQgTAAgMgLQgLgKAAgSQAAgUAPgLQAPgLAaAAQAGAAADACQAEACAAAEQAAAHgJAAQgMAAgIAHQgIAFABALQgBALAHAFQAGAHAMgBQALAAAGgFQAFgGAAgNIAAgvQAAgLgFgHQgEgFgJgBQgGAAgFAEQgGACgFAGIgDADQgHAKgJAAQgFAAgDgDQgDgEAAgFQAAgMAPgJQAPgHAXAAQANAAALADQAJAEAGAHQAEAFABAIQACAHAAASIAAAoIABALQACAEACABIAEABQAIACAAAFQAAAFgJAGQgIAEgLAAQgGAAgGgGg");
	this.shape_25.setTransform(25.3,-42.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E46").s().p("Ag3BNQgPgRAAgcQAAgfARgSQASgUAbAAIAIABQAEABACADQACADAAADQAAAHgIAAIgDAAIgEAAQgNAAgJALQgJALABAUQAAAVAJAOQAJANAOAAQANAAAHgHQAIgIgBgOIAAgjIAAg5QAAgJgBgEQgCgDgEgCIgEgBQgIgCAAgFQAAgDADgDQADgCAKgEIAOgEIAMgBQAFAAABACQACADAAAFIAAAHIgBBOIABA1QAAAMACACIAJACQAHACAAAEQAAAGgSAGIgNAEIgKABQgDAAgCgCQgBgCAAgEIAAgHIgBgCIgBgBIgDADIgGAEQgIAGgGACQgHADgJAAQgXAAgPgRg");
	this.shape_26.setTransform(11.2,-45.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E46").s().p("AgWBbQgGgCAAgGQAAgEAGgCIADgCQAEgCABgEQABgEAAgKIAAgIIAAgLIAAgNIAAgZQgBgGgEgBIgFgCQgIgDAAgEQAAgDACgCQADgDAFgCIATgGIANgCQADAAACACQABADAAAFIAAAIIAAAGIgBAfIAAABIAAAfIABARQABAFADACIAEACQAHACAAAFQAAAFgGACQgGACgRAAQgTAAgGgCgAgPg/QgFgFAAgGQAAgHAGgGQAGgFAIAAQAIAAAFAFQAGAFAAAHQgBAGgFAFQgHAFgIAAQgHAAgGgEg");
	this.shape_27.setTransform(-0.4,-45.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#006E46").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_28.setTransform(-7.7,-45.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#006E46").s().p("AguAwQgRgTgBgdQABgbASgTQAUgTAbAAQAcAAARASQARARAAAcQABAdgUAUQgSATgbAAQgcAAgSgSgAgXglQgIAKAAARQAAAZALARQAKAQAPAAQAMAAAIgKQAHgLABgRQAAgYgLgQQgLgRgOAAQgNAAgHAKg");
	this.shape_29.setTransform(-18.2,-42.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#006E46").s().p("AAcBaQgGgCAAgGQgBgFAIgDIAGgDQACgCABgIIABgdIgBgSIgBgFQgBgDgGgBQgGgBgYAAIgbABQgGABgDACIgBAEIAAAJIAAALIAAAdQABAIACACIAGADQAIADAAAFQAAAGgIACQgGACgVAAQgTAAgIgCQgHgCAAgGQABgFAHgDIAGgDQACgCACgQIABg2IgBgvQgBgTgCgCQgBgCgHgDQgHgDAAgFQABgFAFgCQAGgCAXAAQAWAAAGACQAFACABAFQAAAFgIADIgGADQgCACgBAIIAAAlQAAAFAEACQAFACASAAIAKAAIAbgBQAHgBADgBIABgDIABgFIAAgGIgBgfQgBgGgCgCIgGgDQgIgDABgFQAAgFAFgCQAHgCAVAAQAYAAAFACQAFACAAAFQABAGgJACIgFADQgCACgCARIgBAzIABAxQABATACADQABACAHACQAGADAAAFQABAGgIACQgGACgVAAQgUAAgHgCg");
	this.shape_30.setTransform(-34.9,-45.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.smallbitesplatters, new cjs.Rectangle(-71,-62.4,142,124.8), null);


(lib.seventeenvidrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-46.5,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenvidrollover, new cjs.Rectangle(-64.5,-63.2,129,33.5), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-46.5,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-64.5,-63.2,129,33.5), null);


(lib.seventeenordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASAjIgSg0IgQA0IgPAAIgYhGIAPAAIAQA1IABAAIARg1IAOAAIARA1IAQg1IAPAAIgYBGg");
	this.shape.setTransform(26.8,-46.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAiQgHgCgFgFQgFgFgDgHQgDgHAAgIQAAgHADgIQADgGAFgFQAFgFAHgDQAHgDAHAAQAIAAAHADQAHADAFAFQAGAFACAGQADAIAAAHQAAAIgDAHQgCAHgGAFQgFAFgHACQgHADgIAAQgHAAgHgDgAgJgXQgFACgDAEQgDADgBAFQgCAEAAAFQAAAFACAEQABAFADAEQADAEAFACQAEABAFAAQAGAAAEgBQAFgCADgEQADgEABgFQACgEAAgFQAAgFgCgEQgBgFgDgDQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_1.setTransform(16.4,-46.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASAkIAAgmIgBgIIgCgHIgFgFQgEgCgEAAQgIABgFAFQgGAHAAALIAAAkIgNAAIAAg2IAAgIIgBgIIANAAIABAHIAAAFIAAAAIAEgFIAFgFIAHgDIAHgBQAGAAAFACQAGADACAEQAEAEACAFQABAGAAAFIAAArg");
	this.shape_2.setTransform(7.5,-46.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA2IAAhqIAOAAIAAALIABAAQADgFAHgEQAGgDAIgBQAIAAAHADQAGADAFAFQAFAGACAGQADAHAAAIQAAAHgDAIQgCAFgFAFQgFAFgGADQgHADgIAAQgHABgGgEQgHgDgEgGIgBAAIAAAugAgJgoQgFACgDAEIgFAIIgBAKQAAAFABAEQACAFADADQADAEAFACQAEABAFAAQAFAAAFgBQAEgDADgEQADgCACgFIABgJIgBgKQgCgFgDgDQgDgEgEgCQgFgCgFAAQgFAAgEACg");
	this.shape_3.setTransform(-5.2,-44.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgOAiQgHgCgFgFQgFgFgDgHQgDgHAAgIQAAgHADgIQADgGAFgFQAFgFAHgDQAHgDAHAAQAIAAAHADQAHADAFAFQAGAFACAGQADAIAAAHQAAAIgDAHQgCAHgGAFQgFAFgHACQgHADgIAAQgHAAgHgDgAgJgXQgFACgDAEQgDADgBAFQgCAEAAAFQAAAFACAEQABAFADAEQADAEAFACQAEABAFAAQAGAAAEgBQAFgCADgEQADgEABgFQACgEAAgFQAAgFgCgEQgBgFgDgDQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_4.setTransform(-14.7,-46.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASA5IAAgoIgBgIQgBgEgCgDQgBgCgDgCQgEgBgEAAQgEAAgDABQgEACgCACQgGAGAAALIAAAmIgOAAIAAhxIAOAAIAAA1IABAAQACgFAGgEIAHgCIAGgBQAHAAAFACQAFACADAEIAFAIQACAGAAAGIAAAsg");
	this.shape_5.setTransform(-23.6,-48.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA0QgJgEgGgHIAMgKQADAFAHAEQAGADAHAAIAHgBQAEgBACgCQADgCADgEQACgDAAgFQAAgFgCgDQgDgDgDgCIgIgEIgJgEIgJgDQgFgBgEgEQgEgDgDgFQgCgFAAgHQAAgIADgGQADgGAFgDQAGgEAGgCQAGgCAGAAIAJABIAJADQAIADAEAFIgKALQgDgFgGgCQgFgDgGAAIgHABIgHADIgEAFQgCAEAAAEQAAAEACADIAEAFIAHAEIAHADIALADIAKAFQAFADADAGQADAFAAAIQAAAIgEAGQgCAGgGAEQgFAEgGACQgHACgGAAQgKAAgKgEg");
	this.shape_6.setTransform(-32.4,-48);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenordernow, new cjs.Rectangle(-38.6,-59.3,73.2,22.4), null);


(lib.nineteentrable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentable();
	this.instance.parent = this;
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteentrable, new cjs.Rectangle(-80,-300,160,600), null);


(lib.nineteengrapes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-43.5,-72.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteengrapes, new cjs.Rectangle(-43.5,-72.5,87,145), null);


(lib.nineteencookies = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencrackers();
	this.instance.parent = this;
	this.instance.setTransform(-15,-32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencookies, new cjs.Rectangle(-15,-32,30,64), null);


(lib.nineteencheese_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencheese();
	this.instance.parent = this;
	this.instance.setTransform(-25,-66);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencheese_1, new cjs.Rectangle(-25,-66,50,132), null);


(lib.nineteenbottomright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-51.5,-82);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteenbottomright_1, new cjs.Rectangle(-51.5,-82,103,164), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgL3guZIXvAAMAAABc0I3vAAg");
	this.shape.setTransform(0,0,1.046,1.008);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-80.5,-300.5,161,601), null);


(lib.greenlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.268,0.268);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.268,0.268);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.268,0.268);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14.1,23.7,0.268,0.268);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(6.1,23.7,0.268,0.268);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.268,0.268);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.268,0.268);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.268,0.268);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.268,0.268);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-5.6,8.1,0.268,0.268);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.268,0.268);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(29.5,8.1,0.268,0.268);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-20,-9.9,0.268,0.268);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.268,0.268);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.268,0.268);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.268,0.268);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.greenlogo, new cjs.Rectangle(-46.9,-46.9,93.9,93.9), null);


(lib.getpartystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgqAyIgEgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAhaIABgEQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAlAAIAKABIAKACQAKAEAHAHQAIAGAEAJIADAKIABAKQAAAMgEAJIgFAIIgHAIIgIAFIgJAFQgKADgKAAgAgbgeQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIAAA2QAAABABAAQAAABAAAAQAAABABAAQAAAAAAABIAEABIASAAQAGAAAHgDQAGgCAFgEQAFgEADgGQACgGABgIQgBgGgCgGQgDgGgFgFQgFgEgGgCQgHgCgGAAIgSAAIgEABg");
	this.shape.setTransform(54.5,9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AghAyIgDgBIgCgCIAAhdQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIBGAAIACACIABADIAAADIAAADIAAAEIgDADIg0AAIgCABIgCADIAAAOQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIADABIAhAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABADIAAAEIAAACQAAAEgDACIghAAIgDABIgCAEIAAAPIABAEIAEABIAzAAQADACAAAEIAAADIAAAEIgBADQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(43.9,9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgBAzIgFgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBIgEgBIgIAAIgIAAIgEABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgBgFIAAgDIABgDIABgDIADgBIBFAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIABAFIAAADIgBADIgBADIgDACIgUAAIgEABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAABIAABIQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgDABIgEABg");
	this.shape_2.setTransform(34.4,9.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAZAzIgCgBIgCgBIgCgBIgQgaIgDgEIgEgBIgNAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAIgEACIgEAAIgEAAIgEgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgBAAgBIAAhbQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIADgBIAqAAQAIAAAGACQAGADAGAEQAEAEADAHQACAGABAIQAAAJgDAFQgEAEgDADIgIAGQgCACAAACIAAACIADAGIAGAIIAFAIIADAFIgCADIgDACIgDACIgEAAgAgUggQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAABIAAAWQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQABAAAAAAQABAAAAAAQABAAAAAAIAVAAIAHAAIAGgDQACgCACgEQABgDABgEQgBgIgFgFIgGgDIgHgBIgVAAIgEABg");
	this.shape_3.setTransform(25.5,9.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AAoAzIgEAAIgEgBQgEgBgBgCIgFgOIgCgCIgDAAIghAAIgBAAIgBABIgCABIgBAAIgGAOIgBACIgDABIgDAAIgDABIgCgBIgEAAIgDgBIAAgBIAohfIADgCIADgBIAEABQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAIAnBeIAAABQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDABgAgBgNIgBACIgCAFIgDAFIgDAFIgBAFIgBACIABACIACABIATAAIACgBIABgBIgCgFIgDgIIgDgIIgDgFIgCgBIgBAAg");
	this.shape_4.setTransform(15,9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgBAzIgFgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBIgEgBIgIAAIgIAAIgEABQAAAAgBAAQgBgBAAAAQgBAAAAgBQgBAAAAgBIgBgFIAAgDIABgDIABgDIADgBIBFAAQAAAAABAAQABAAAAABQABAAAAAAQAAABABAAIABAFIAAADIgBADIgBADIgDACIgUAAIgEABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAABIAABIQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgDABIgEABg");
	this.shape_5.setTransform(6,9.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgVAxQgLgFgJgHIgBgCIAAgDIABgCIAEgEIADgDIAEAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAIAHAFIAIAEQAFACAGAAIAIgBIAIgCIAFgFQADgDAAgEQAAgEgDgDIgHgDIgLgDIgLgBIgLgCQgHgCgEgDQgEgCgDgGQgDgFAAgHQAAgIAEgGQAEgFAGgEQAGgEAIgBQAHgCAFAAIAKABIAKABIAKAEIAIAGIAAACIABACIgCAEIgCACIgFADIgDABIgDgBQgFgFgHgCQgFgDgHAAIgHABIgGACQgDABgCADQgCADAAAEQgBAGAFACQAFADAHAAIAPACQAIACAHADQAIACAEAFQAFAGAAAKQAAAIgEAHQgEAGgHAEQgGAEgIACQgHACgHAAQgLAAgKgDg");
	this.shape_6.setTransform(-3.1,9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgDA1IgCgBIgCgBIgBgCIAAgkIgBgGIgDgFIgdgsIAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAIADgDIADgBIAEgBIADABIACACIAUAgIACACIACABIACgBIACgCIAUggIADgDIADgBIAEABIADACIAEACIABADIAAABIgBABIgdAsIgCAGIgBACIAAADIAAAjQgBAEgEAAIgFABg");
	this.shape_7.setTransform(-16.8,8.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgBAzIgFgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBIgEgBIgIAAIgIAAIgEABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgBgFIAAgDIABgDIABgDIADgBIBFAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIABAFIAAADIgBADIgBADIgDACIgUAAIgEABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAABIAABIQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIgDABIgEABg");
	this.shape_8.setTransform(-25.5,9.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AAZAzIgCgBIgCgBIgCgBIgQgaIgDgEIgEgBIgNAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAIgEACIgEAAIgEAAIgEgBQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgBAAgBIAAhbQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIADgBIAqAAQAIAAAGACQAGADAGAEQAEAEADAHQACAGABAIQAAAJgDAFQgEAEgDADIgIAGQgCACAAACIAAACIADAGIAGAIIAFAIIADAFIgCADIgDACIgDACIgEAAgAgUggQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAABIAAAWQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQABAAAAAAQABAAAAAAQABAAAAAAIAVAAIAHAAIAGgDQACgCACgEQABgDABgEQgBgIgFgFIgGgDIgHgBIgVAAIgEABg");
	this.shape_9.setTransform(-34.4,9.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAoAzIgEAAIgEgBQgEgBgBgCIgFgOIgCgCIgDAAIghAAIgBAAIgCABIgBABIgBAAIgGAOIgBACIgDABIgDAAIgDABIgCgBIgEAAIgDgBIAAgBIAohfIADgCIADgBIAEABQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAIAoBeIAAABQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDABgAgBgNIgBACIgCAFIgDAFIgDAFIgBAFIgBACIABACIACABIATAAIACgBIABgBIgCgFIgDgIIgDgIIgDgFIgCgBIgBAAg");
	this.shape_10.setTransform(-44.8,9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgfAzIgEAAQgEAAgCgEIAAheQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABgBIADAAIAqAAQAIAAAGACQAGACAFAEQAFAEADAGQADAGAAAIIgBAEIgBAFQgEAJgGAEQgHAEgIACQgIACgIgBIgRAAIgCABIgBABIgBAEIAAAeIgDADIgDABgAgVgfIgBAEIAAARIABADQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAAAIAYAAIAHgBIAFgCQACgBABgEQACgCAAgDQAAgDgCgDIgDgEIgFgDIgFgBIgZAAQgBAAAAABQgBAAgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_11.setTransform(-54.2,9.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AghAyIgDgBIgCgCIAAhdQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIBGAAIACACIABADIAAADIAAADIAAAEIgDADIg0AAIgCABIgCADIAAAOQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIADABIAhAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABADIAAAEIAAACQAAAEgDACIghAAIgDABIgCAEIAAAPIABAEIAEABIAzAAQADACAAAEIAAADIAAAEIgBADIgDABg");
	this.shape_12.setTransform(27.2,-9.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AAbAzQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIAAgjQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAAAIgiAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAAAQgBABAAAAQAAABAAAAIAAAjQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAIgDABIgEAAIgEgBIgDgBIgDgCIAAhfIADgDIADgBIAEAAIADAAQAEAAACAEIAAAgIABAEQABAAAAABQAAAAABAAQAAAAABAAQAAABABAAIAiAAIAEgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIAAggQACgDADAAIAGgBIAEABIAEADIgBBfQgBADgDAAIgGABg");
	this.shape_13.setTransform(16.4,-9.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgBAzIgFgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBIgEgBIgIAAIgIAAIgEABQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgBgFIAAgDIABgDIABgDIADgBIBFAAQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIABAFIAAADIgBADIgBADIgDACIgUAAIgEABQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAABIAABIQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgDABIgEABg");
	this.shape_14.setTransform(6.7,-9.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgBAzIgFgCQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBIgEgBIgIAAIgIAAIgEABQAAAAgBAAQgBgBAAAAQgBAAAAgBQgBAAAAgBIgBgFIAAgDIABgDIABgDIADgBIBFAAQABAAAAAAQABABAAAAQABAAAAAAQAAABABAAIABAFIAAADIgBADIgBADIgDACIgUAAIgEABQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAABIAABIQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgDABIgEABg");
	this.shape_15.setTransform(-5.8,-9.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AghAyIgDgBIgCgCIAAhdQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIBGAAIACACIABADIAAADIAAADIAAAEIgDADIg0AAIgCABIgCADIAAAOQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIADABIAhAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABADIAAAEIAAACQAAAEgDACIghAAIgDABIgCAEIAAAPIABAEIAEABIAzAAQADACAAAEIAAADIAAAEIgBADIgDABg");
	this.shape_16.setTransform(-14.4,-9.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgHAzIgLgDIgJgEIgIgGQgEgEgCgFIgFgJQgFgJAAgLIABgKIAEgKQAEgKAHgGIAIgHIAJgFIALgDIAJAAIAMAAIALAEQALAFAHAJIABABIgCAEIgDAEIgEACIgDACQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgGgEIgIgFQgFgCgHAAQgGAAgGADQgGADgFAEQgFAFgDAGQgCAHAAAGQAAAHACAGQADAHAFAEQAFAFAGADQAGADAGAAIAHgBIAHgCQAEAAADgDIAEgGIABgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBgBAAIgDgBIgSAAIgDgBIgBgEIAAgDIAAgEIABgDIACgCIArAAIABABIACAAQACAFAAAFIAAAFIgBADQgDAIgFAGQgFAGgHAEQgGAEgHACQgIADgIAAIgJgCg");
	this.shape_17.setTransform(-25.8,-9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getpartystarted, new cjs.Rectangle(-61.9,-18.7,123.8,37.4), null);


(lib.bottomleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenshrimp();
	this.instance.parent = this;
	this.instance.setTransform(-46.5,-58.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottomleft, new cjs.Rectangle(-46.5,-58.5,93,117), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// cta-rollover
	this.instance = new lib.seventeenvidrollover();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.5,-63.2,129,33.5);


// stage content:
(lib.wideskyscrapernineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_74 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		
		console.log("this frame works");
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_85 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(74).call(this.frame_74).wait(11).call(this.frame_85).wait(2));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(82.2,302,0.797,0.919,0,0,0,0.1,0.4);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(87));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(87));

	// fade-from-white
	this.instance_1 = new lib.whiterectanglefade();
	this.instance_1.parent = this;
	this.instance_1.setTransform(91,300.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(78));

	// kale-logo
	this.instance_2 = new lib.greenlogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,36.9);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.02,scaleY:0.02},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(65));

	// shop-now
	this.instance_3 = new lib.seventeenordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,383);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(74).to({alpha:1},10).wait(3));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(80,382.8);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(74).to({alpha:1},10).wait(3));

	// cta-rectangle
	this.instance_4 = new lib.seventeenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(80,382.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(74).to({alpha:1},10).wait(3));

	// getp party started
	this.instance_5 = new lib.getpartystarted();
	this.instance_5.parent = this;
	this.instance_5.setTransform(80,158.1);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(46).to({alpha:1},10).wait(31));

	// HOLIDAY-SMALL-BITES
	this.instance_6 = new lib.smallbitesplatters();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80,244.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(59).to({alpha:1},10).wait(18));

	// cheese
	this.instance_7 = new lib.nineteencheese_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(25,95);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(14).to({alpha:1},10).wait(63));

	// BOTTOM-RIGHT
	this.instance_8 = new lib.nineteenbottomright_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(108.5,439.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(19).to({alpha:1},10).wait(58));

	// bottom-left
	this.instance_9 = new lib.bottomleft();
	this.instance_9.parent = this;
	this.instance_9.setTransform(46.5,541.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(24).to({alpha:1},10).wait(53));

	// crackers
	this.instance_10 = new lib.nineteencookies();
	this.instance_10.parent = this;
	this.instance_10.setTransform(15,459);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(29).to({alpha:1},10).wait(48));

	// grapes
	this.instance_11 = new lib.nineteengrapes();
	this.instance_11.parent = this;
	this.instance_11.setTransform(116.5,72.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(9).to({alpha:1},10).wait(68));

	// table
	this.instance_12 = new lib.nineteentrable();
	this.instance_12.parent = this;
	this.instance_12.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(87));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(68,274,206.1,652.2);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.png?1511027923959", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;